version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  webapi:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    container_name: webapi_container
    depends_on:
      - mongodb
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Mongo__ConnectionString=mongodb://mongodb:27017
      - Mongo__Database=appdb
      - Redis__Configuration=redis:6379
      - Cache__ProductTtlSeconds=600
    ports:
      - "8080:8080"

volumes:
  mongo_data: